config/routes.rb
Rails.application.routes.draw do
  devise_for :users

root to: "contents#index"
  get 'contents/download/:id',to: "contents#download",as: "download_file"
  resources :contents do
    resources :comments, only: [:create, :destroy]
  end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :content
end

app/models/content.rb
class Content < ApplicationRecord
  mount_uploader :file, FileUploader
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

def after_sign_in_path_for(resource)
  root_path
end

def after_sign_out_path_for(resource)
  new_user_session_path
end

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @content = Content.find(params[:content_id])
    @comment = @content.comments.create(comment_params)
    if @comment.save
      flash[:success] = 'コメントを投稿しました'
      redirect_to content_path(@content)
    else
      flash[:danger] = 'コメント投稿に失敗しました'
      redirect_back(fallback_location: contents_path)
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to contents_path(@content)
  end


private

def comment_params
  params.require(:comment).permit(:comment)
end

end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: %i[ show edit update destroy download]
  # GET /contents or /contents.json
  def index
    @contents = Content.all
  end

  # GET /contents/1 or /contents/1.json
  def show
  end

  # GET /contents/new
  def new
    @content = Content.new
  end

  # GET /contents/1/edit
  def edit
  end

  # POST /contents or /contents.json
  def create
    @content = Content.new(content_params)

    respond_to do |format|
      if @content.save
        format.html { redirect_to content_url(@content), notice: "Content was successfully created." }
        format.json { render :show, status: :created, location: @content }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contents/1 or /contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to content_url(@content), notice: "Content was successfully updated." }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1 or /contents/1.json
  def destroy
    @content.destroy

    respond_to do |format|
      format.html { redirect_to contents_url, notice: "Content was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def download
    send_data(@content.file.read, :filename => @content.file_identifier)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_content
      @content = Content.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def content_params
      params.require(:content).permit(:name, :body, :file)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/_content.html.erb
<div id="<%= dom_id content %>">
  <p>
    <strong>Name:</strong>
    <%= content.name %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= content.body %>
  </p>

  <p>
    <strong>File:</strong>
    <%= content.file %>
  </p>

</div>

app/views/contents/_form.html.erb
<%= form_with(model: content) do |form| %>
  <% if content.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
        <% content.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.label :file, style: "display: block" %>
    <%= form.file_field :file %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/contents/edit.html.erb
<div id="edit", class="big-bg">
<h1>Editing content</h1>

<%= render "form", content: @content %>
<td><%= button_to '削除', @content, method: :delete, data: { confirm: 'Are you sure?' } %>

<div>
<div>
 <!--<%= link_to "Show this content", @content %> |
   link_to "Back to contents", contents_path %>-->
</div>
</div>

app/views/contents/index.html.erb
<p id="notice"><%= notice %></p>
<div id="index" class="big-bg">
<div style="text-align: center">
  まだ未完成の曲、生まれたばかりの曲たちの最初のリスナーに
  <br>
  <br>
</div>
<br>
<br>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <!--<th>File</th>-->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <br>
    <% @contents.each do |content| %>
      <tr>
        <td><%= link_to content.name, content %></td>
        <!--<td><%= content.file_identifier %></td>-->
        <!--<td><%= button_to '編集', edit_content_path(content) %></td> -->
        <!--<td><%= button_to '削除', content, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
    <br>
  </tbody>
</table>


</div>

app/views/contents/new.html.erb
<div id="new", class="big-bg">
  <h1>New content</h1>

<%= render "form", content: @content %>


<div>
  <!--<%= link_to "Back to contents", contents_path %>-->
</div>
</div>

app/views/contents/show.html.erb
<p style="color: green"><%= notice %></p>
<div id="show" class="big-bg">

<p>
<br>
  <strong>Name:</strong>
  <%= @content.name %>
</p>

<p>
<br>
  <strong>Body:</strong>
  <%= @content.body %>
</p>

<p>
<br>
  <strong>File:</strong>
  <audio src= <%= @content.file %> controls="">
  </audio>
</p>
<p><%= link_to "edit", edit_content_path(@content) %>

<h2>コメント一覧<h2>
  <% @content.comments.each do |comment| %>
    <p><%= comment.comment %></p>
  <% end %>
<br>
<h2>コメント投稿<h2>
<%= form_with(model:[ @content, @content.comments.build ], local:true) do |form| %>

    <div class="form-group">
        <p>
            <!--<%= form.label 'コメント(255文字未満)' %>-->
            <%= form.text_area :comment,class: 'form-control' %>
        </p>
    </div>
    <div class="form_action row">
        <%= form.submit 'コメント投稿',class: 'btn btn-primary' %>
    </div>
<% end %>


<div>
  <!--<%= link_to "Back to contents", contents_path %>-->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  
    <title>MusicPoster</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
    <div class="notification is-info">
      <p class="notice"><%= notice %></p>
    </div>
    <% end %>

   <% if flash[:alert] %>
    <div class="notification is-danger">
      <p class="alert"><%= alert %></p>
    </div>
    <% end %>

    
    <nav class="navbar is-warning">
      <div class="navbar-brand">
    <%= link_to root_path, class: "navbar-item" do %>
      <h1 class="title is-4" style="font-family: cursive;">musicposter</h1>
    <% end %>
    <div class="navbar-burger burger" data-target="navbarExampleTransparentExample">
          <span></span>
          <span></span>
          <span></span>
      </div>
    </div>
  

    <% if user_signed_in? %>
      <!--<div id="navbarExampleTransparentExample" class="navbar-menu">
        <div class="navbar-item">
          <%= link_to "コンテンツ一覧", contents_path, class: "navbar-item button is-warning is-light" %>
        </div>-->
      

      <div class="navbar-end">
        <div class="navbar-item">
          <div class="field is-grouped">
            <p class="control">
              <%= link_to 'New Content', new_content_path %>
              <%= button_to "ログアウト", destroy_user_session_path, method: :delete %>
            </p>
          </div>
        </div>
      </div>
    </div>

    <% else %>
      <div id="navbarExampleTransparentExample" class="navbar-menu">
        <div class="navbar-end">
            <div class="navbar-item">
              <div class="field is-grouped">
                <p class="control">
                  <%= link_to "ログイン", new_user_session_path, class: "button is-warning is-light" %>
                </p>
                <p class="control">
                  <%= link_to "新規登録", new_user_registration_path, class: "button is-warning is-light" %>
                </p>
              </div>
            </div>
          </div>
        </div>
    <% end %>

   </nav>
    <%= yield %>
  </body>
</html>